#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import os
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

host = data.get("host", "")


# This is specific to you module, so you need to change it accordingly.
def generate_random_password(length):
    # Generate random bytes and convert them to a hexadecimal string
    random_bytes = os.urandom(length)
    password = random_bytes.hex()
    return password[:length]


if os.path.exists("app-db.env"):
    dt = agent.read_envfile("app-db.env")
    APP_KEY = dt.get("APP_KEY", generate_random_password(64))
else:
    APP_KEY = generate_random_password(64)

APP_URL = "https://" + host
agent.write_envfile("app.env", {"APP_URL": APP_URL, "APP_KEY": APP_KEY})
# This is specific to you module, so you need to change it accordingly.
# we read a json stdin {"vars1":true, "var2":"foo", "vars3": 3} and we writ it to .config/state/environment
# Upper case to set environment variable and minor case to read from stdin

# agent.dump_env()
