#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import os
import sys
import agent
import base64

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

host = data.get("host", "")


def generate_laravel_app_key():
    key = os.urandom(32)  # 32 bytes for AES-256
    return "base64:" + base64.b64encode(key).decode("utf-8")


if os.path.exists("app-db.env"):
    dt = agent.read_envfile("app-db.env")
    APP_KEY = dt.get("APP_KEY", generate_laravel_app_key())
else:
    APP_KEY = generate_laravel_app_key()

APP_URL = "https://" + host
agent.write_envfile("app.env", {"APP_URL": APP_URL, "APP_KEY": APP_KEY})

# agent.dump_env()
